### ISSUE TITLE
tanítványság

### ISSUE THREAD

**Issue by gyuris** [laszlonemeth/magyarispell#1]
Látom a „mentorál” ige nemrég bekerült, ami nekem is hiányzott nemrég. 

De ha egyesével is foglalkozol vele, akkor nekem még a „tanítványság” szó hiányzik nagyon. Keresztény szóhasználaton kívül nem tudom hol használják még.

Itt kell az ilyeneket bejelenteni?

**Comment by laszlonemeth** [comment]
Igen, itt megmarad a nyoma, köszönöm szépen! :) Felvettem a szót. A speciális szótárakat, így a teológia modult is szeretném majd a LibreOffice-ban beállítani, mint nem bekapcsolt, de a LibreOffice-szal érkező felhasználói szókincset a jövőben, mivel most már van arra lehetőség, hogy ezeket toldalékolja is a LibreOffice....
