### ISSUE TITLE
repedtfazék, tiltott szavak

### ISSUE THREAD

**Issue by swan46** [laszlonemeth/magyarispell#17]
A repedtfazék szó godo2/fonev_morfo2.2-ben tiltottnak van jelölve, helytelenül.
Általában túl sok teljesen helyes magyar szó van tiltottnak jelölve, láthatólag valamiféle szeszélytől indíttatva. Ezt sürgősen helyesbíteni kellene.

**Comment by laszlonemeth** [comment]
A szótár a magyar nyelv Magyar Tudományos Akadémia által meghatározott helyesírási szabályait követi. Az AkH. 12. kiadása, annak szójegyzéke, illetve a Magyar helyesírási szótárnak megfelelően: repedt fazék, ill. repedtfazék-hangú. (l. még https://hu.wikipedia.org/wiki/Mozg%C3%B3szab%C3%A1ly). Kérem, hogy a fentiek alapján szűkítse a beküldött szólistákat, mert azok jelentős része nem felel meg a jelenleg érvényben lévő magyar helyesírási szabályoknak!

**Comment by swan46** [comment]
Kár, hogy ilyen obskurus (gyanús) szabályokhoz való ragaszkodás lenyomja az egyébként kétségtelenül magas színvonalat.

**Comment by Kixidevel** [comment]
@swan46 
László csupán arra utalt, hogy NEM MINDEN szó, amit megadtál, tényleg helyes. A magyar helyesírás alapja a központilag Magyar Tudományos Akadémia által meghatározott helyesírás. Ha olyan ad hoc szavakat is bevennénk, mint pl.: Tito neve hosszú magánhangzókkal, vagy a kubikusok (kubikosok kubikolnak) , káosz lenne a vége. Kétségtelen, hogy voltak jó szavaid is, csupán utána kell nézned, valóban helyes-e, amit megadtál, és ha igen, küldd át!

**Comment by swan46** [comment]
A nyelvet nem egy obskurus "bizottság" határozza meg, hanem az emberek, akik beszélik azt. Az úgynevezett "Magyar Tudományos Akadémia" eleve gyanús társaság. Ha vannak szavak, melyek helyesírása több módon létezik és helyes, abban semmi különös nincs. Azután vannak régies, ma már nem használt szavak, melyek léteznek és helyesek, noha ma már nem használatosak. Éppen a repedtfazék szó az, amely különírva mást jelent, mint együtt, és nem lenne szabad a tiltott listára tenni. De sok más, hasonlóan hajmeresztő szó van a tiltott listán. Föltettem 23 ezer szót, melyek nagy része helyes, kézzel és guglival van ellenőrizve, és az ellenőrző mégsem ismeri fel őket. Viszont nagyon  sok, nyilvánvalóan helytelen szót generál és ismer el obskurus összetettszó-képzésével.  Kár egy jó minőségű, és tényleg innovatív terméket ilyen dolgokkal elrontani.

**Comment by swan46** [comment]
> A szótár a magyar nyelv Magyar Tudományos Akadémia által meghatározott helyesírási szabályait követi. Az AkH. 12. kiadása, annak szójegyzéke, illetve a Magyar helyesírási szótárnak megfelelően: repedt fazék, ill. repedtfazék-hangú. (l. még https://hu.wikipedia.org/wiki/Mozg%C3%B3szab%C3%A1ly). Kérem, hogy a fentiek alapján szűkítse a beküldött szólistákat, mert azok jelentős része nem felel meg a jelenleg érvényben lévő magyar helyesírási szabályoknak!

A repedtfazék szó 4 szótagú, 2 tagból áll, tehát a 6:3 szabály alapján nem zárható ki az összetett szavak közül. Ez HIBA. Lásd:
https://e-nyelv.hu/2009-11-30/6-3-as-szabaly-a-szotagszamlalas-szabalya/
