### ISSUE TITLE
Mozilla szótár frissítés

### ISSUE THREAD

**Issue by crash5** [laszlonemeth/magyarispell#3]
Tervezik frissíteni a friss szótár alapján a Mozilla szótár beépülőjét?

Jelenleg csak az 1.6.1-es verzió érhető el, ami még a 2015 decemberi állapotot tükrözi. (Ha nincs felelőse a frissítésnek szívesen elkészítem, de én nem tudom lecseréltetni a hivatalos verziót a Mozilla oldalán)

**Comment by crash5** [comment]
2018. Nov. 16-án megtörtént a frissítés, így zárom az issuet.

**Comment by laszlonemeth** [comment]
Kedves Imre! Köszönöm a javaslatot! Az FSF.hu Alapítvány aktivistája, Meskó Balázs frissítette a szótárat, köszönhetően az Ön hibabejelentésének is! Üdvözlettel: Németh László
