### ISSUE TITLE
házt, lázt, mázt, vázt

### ISSUE THREAD

**Issue by swan46** [laszlonemeth/magyarispell#46]
Nem fogadja el csak a hosszabb verziót: házat, lázat, mázat, vázat.
Sajnos nem találtam példát, hogy hogy lehet rávenni, hogy elfogadja őket. (kivéve a ragozatlanba tevést, amit nem tartok nagyon elegánsnak)

**Comment by laszlonemeth** [comment]
A felsorolt alakokat a köznyelv nem használja.

A felvétel lehetséges a ragozatlan szavak közé való helyezéssel.

Köszönöm a bejelentést!
