### ISSUE TITLE
teljesítményközpontú

### ISSUE THREAD

**Issue by urbalazs** [laszlonemeth/magyarispell#49]
Az [egybe-külön](https://helyesiras.mta.hu/helyesiras/default/kulegy) szerint ezt egybe kell írni és helyes szó, miközben a szótár hibásnak jelzi.

> A „teljesítmény” főnevet és a „központú” melléknevet egybeírjuk az alábbi szabály alapján:
> A jelentéssűrítő összetételeket egybeírjuk. [[AkH11-129](https://helyesiras.mta.hu/helyesiras/default/akh11#129), [AkH12-111](https://helyesiras.mta.hu/helyesiras/default/akh12#111)]

**Comment by laszlonemeth** [comment]
A 6-3-as szabály szerint a melléknévképzők, mint az -ú, beleszámít a szótagszámba, így a teljesítmény-központú kötőjellel írandó (az AkH. 12. kiadása csak a -i melléknévképzőt jelölte meg új kivételként: https://hu.wikipedia.org/wiki/A_helyes%C3%ADr%C3%A1si_szab%C3%A1lyzat_12._kiad%C3%A1s%C3%A1nak_v%C3%A1ltoz%C3%A1sai). 

Köszönöm szépen a visszajelzést!
