### ISSUE TITLE
appellál, appelláció

### ISSUE THREAD

**Issue by urbalazs** [laszlonemeth/magyarispell#51]
Az appellál, appelláció hiányzik a szótárból. Lásd: https://mek.oszk.hu/00000/00060/html/006/pc000602.html

**Comment by laszlonemeth** [comment]
A szó mai helyesírása, amelyet a szó tartalmaz, az apellál: https://mek.oszk.hu/adatbazis/magyar-nyelv-ertelmezo-szotara/szotar.php?szo=APELL%C3%81L&offset=69&kezdobetu=A

Az apelláció új szóként felvételre került.

Köszönöm a hibajelzést!
