### ISSUE TITLE
Encoding error

### ISSUE THREAD

**Issue by djkris105** [laszlonemeth/magyarispell#6]
Hello,
I'm having problems with the generated file's encoding. The file I'm interested in is _hu_HU_u8_morph_.{aff, dic}, generated by just doing:
`make`

I've tried running the tool _u8myspell_ in the following ways:
`bin/u8myspell hu_HU_u8_morph hu_fix UTF-8`
`bin/u8myspell hu_HU_u8_morph hu_fix latin2`

With no positive results: the output file was even more broken than the source file. I've also tried other common encodings with no success.  
  
Is there any way to fix the issue?

**Comment by andreim14** [comment]
Hello, i'm having the same problem with the morph files

**Comment by djkris105** [comment]
Can no one help me understand what's going on? Is the project dead?

**Comment by laszlonemeth** [comment]
Hunspell's file format is not an UTF-8 encoded text file in the case of SET UTF-8 with the default 8-bit FLAG, see also https://github.com/hunspell/hunspell/issues/559
