### ISSUE TITLE
kötőhabarcs typo

### ISSUE THREAD

**Issue by teddybee** [laszlonemeth/magyarispell#62]
Kötőhabaracs -nak írtátok ami kötőhabarcs.
https://kolor.hu/termekek/jubosan-c110-antikor-kotohabarcs/

**Comment by laszlonemeth** [comment]
Az eleonora modulban lévő szavak alapértelmezés szerint nem szerepelnek a szótárban, mert sok elavult, vagy elavult helyesírású alakot tartalmaznak. Ez nem kerül javításra azért, hogy a régi könyvek lapolvasásához, és eredeti írásmódjának megőrzéséhez használható legyen. Ebben az esetben érdemes a modult a szótárba belefordítani.

Köszönöm a hibajelzést!
