### ISSUE TITLE
helyrajziszámozás, alrészlet, újfelmérés

### ISSUE THREAD

**Issue by urbalazs** [laszlonemeth/magyarispell#63]
A helyrajziszámozás mint főnév és a helyrajziszámozni mint ige többször is szerepel ebben: _44/2006. (VI. 13.) FVM rendelet
az önálló ingatlanok helyrajziszámozásáról és az alrészletek megjelöléséről_

Van benne továbbá egy át-helyrajziszámozni ige is. Ezenkívül az alrészlet és az újfelmérés sem szerepel a szótárban, de a rendeletben igen.

**Comment by laszlonemeth** [comment]
A helyrajziszámozás felvéve. Az ige esetén az egybeírás kevésbé vagy nem indokolt.

Köszönöm a hibajelzést!
