### ISSUE TITLE
funkciógazdag

### ISSUE THREAD

**Issue by urbalazs** [laszlonemeth/magyarispell#69]
A **funkciógazdag** szót nem ismeri fel a szótár helyes szóként.

**Comment by laszlonemeth** [comment]
Szia, Balázs!

A következő foltban pótlásra kerül, mert a Szószablya adatok alapján van mérhető előfordulása:

funkciógazdag	13
funkciógazdagsága	5
funkciógazdagság	3
funkciógazdagságának	2
funkciógazdagságához	1
funkciógazdagságában	1
funkciógazdagok	1
funkciógazdagítása	1

(A legutóbbi folttal (https://github.com/laszlonemeth/magyarispell/commit/4f3129e864e6e3b9fa32b84201fb6431f50477aa) a következők kerültek be:

színgazdag	66
formagazdag	56
információgazdag	51)

Köszönöm a bejelentést!

**Comment by laszlonemeth** [comment]
Javítva  a következő foltban:

commit 1b0ad7def075341d6fa6573684c2623534a6552d
Author: László Németh <nemeth@numbertext.org>
Date:   Sun May 21 13:54:41 2023 +0200

    Terms of hidrology etc. collected by Balázs Úr

Köszönöm még egyszer a hibajelzést!
