### ISSUE TITLE
Ekezet nelkuli Magyar Ispell?

### ISSUE THREAD

**Issue by unpack5** [laszlonemeth/magyarispell#7]
Gepelesben egyre tobben hasznaljak a magyar nyelvet ekezetek nelkul. Ennek sokfele oka lehet: ilyen pl. a tobbnyelvu (munka)kornyezet, ahol kevesbe praktikus tobbfele billentyuzet-kioszast hasznalni, illetve koztuk valtogatni. De ketsegtelenul gyorsabb, kenyelmesebb es egyszerubb is igy gepelni.

A temarol megoszlo velemenyek vannak, 3 eve irt errol a [Nyest](https://www.nyest.hu/hirek/helyesirasi-hiba-e-az-ekezethiany?comments) es a [24.hu](https://24.hu/tudomany/2015/08/08/le-az-ekezetekkel-a-kerdes-csak-az-hogy-igy-is-ertelmes-szoveget-kapunk/).

Velemenyem szerint a technikai fejlodessel meg nagyobb teret fog nyerni ez a hasznalat, es okkal. Nem gondolom, hogy ez egy kizarasos valasztas lenne -- akik valamennyire is hasznaljak az ekezet nelkuli varianst, azok szamara kornyezettol es preferenciatol fuggoen ugyanugy megvan a helye az ekezetes es az ekezet nelkuli irasmodnak is.

Viszont az ekezet nelkuli irasmodnak egy nagy hatranya, hogy nem lehet gepileg ellenorizni a "helyesirasat" (itt pontosabb az elmeleti helyessegrol beszelni), mivel ilyen helyesirasi szotar meg nincs.

Ti mit gondoltok a temarol?

Es mennyire lenne nehez egy ekezet nelkuli Magyar Ispell szotarat letrehozni a meglevo szotar alapjan?

**Comment by laszlonemeth** [comment]
Készítettem egy ilyen szótárváltozatot, de amúgy inkább az automatikus ékezetesítés, ami érdekes nyelvtechnológiai szempontból, és a Hunspell tudott is ilyesmit (most csak a javaslatok szintjént).

Az ékezet nélküli magyar helyesírás-ellenőrző (aff és dic állományok) innen nyerhető egy xpi állományból: https://hup.hu/node/50632

**Comment by unpack5** [comment]
@laszlonemeth Koszonom! Az xpi-t sajnos egyik Mozilla-tipusu programban sem tudom telepiteni, valoszinuleg a regi (15 eves) build miatt nem kompatibilis.

Sajnos a buildek keszitesehez nem ertek es kornyezetem sincs hozza. Megkerhetlek, hogy feltolts egy olyan xpi-t, amit a friss Firefox es Thunderbird beolvas? Vagy ha erre nincs idod, akkor kerhetek segitseget abban, hogy hogyan tudok kesziteni egy ilyet? Nagyon nagy segitseg lenne.

Illetve az sem egyertelmu szamomra, hogy az optacc fajlt le kell-e futtatnom, hogy ekezet nelkulive valjanak a fajlok -- sajnos ehhez is keves vagyok technikailag.
