### ISSUE TITLE
elektroakusztikus gitár

### ISSUE THREAD

**Issue by gyuris** [laszlonemeth/magyarispell#71]
Az elektroakusztikus szót (pl. elektroakusztikus gitár) a LibreOffice (7.5.3.2) hibásnak jelöli meg. Lásd: http://corpus.nytud.hu/cgi-bin/mnszgyak?mode=word&ppos=all&focus=elektroakusztikus&context=c0&sort=total

**Comment by laszlonemeth** [comment]
Javítva a fő ágban.

Köszönöm a hibajelzést!
