### ISSUE TITLE
nemváltó

### ISSUE THREAD

**Issue by urbalazs** [laszlonemeth/magyarispell#74]
A **nemváltó**, **áramnemváltó** stb. szavakat hibásnak jelzi a szótár. Feltételezem, hogy azért, mert a „nem” szót nem főnévként, hanem tagadószóként ismeri fel, és ezért külön akarja írni.

**Comment by laszlonemeth** [comment]
A következő folttal került hozzáadásra:

commit 67770a238a8ab741867d54a1fb35e0598759946e
Author: László Németh <nemeth@numbertext.org>
Date:   Fri Feb 18 09:36:54 2022 +0100

    [Tuna-16] életszerűtlen, filléreskedik, magyartudás...
    
    Suggested by Tuna András:
    
    életszerűtlen
    filléreskedik
    magyartudás
    nemváltás, nemátalakítás, nemváltó, nemátalakító
...

Köszönöm szépen a hibajelzést!
