### ISSUE TITLE
OpenStreetMap

### ISSUE THREAD

**Issue by urbalazs** [laszlonemeth/magyarispell#76]
Az OpenStreetMapet nagyon sok szervezet használja már, ezért az OpenStreetMapnek is benne kellene lennie a szótárban. Kérlek, vedd fel az OpenStreetMapet is. Többes száma nincs, az OpenStreetMapek hibásnak kell maradnia. Az előző mondat csak a különféle ragozott alakok miatt íródott.

**Comment by laszlonemeth** [comment]
Felvéve. Köszönöm a hibajelzést!
