### ISSUE TITLE
Random

### ISSUE THREAD

**Issue by kovacshviktor** [laszlonemeth/magyarispell#77]
Fiatalabb generáció szlengjébe bekerült a "random" szó. Nem ragozzák.

**Comment by laszlonemeth** [comment]
A szó már felvételre került a következő foltban:

commit 68318e88ee9ce90cad6dca5f314bd7e392ec8637
Author: László Németh <nemeth@numbertext.org>
Date:   Mon Jan 16 12:49:09 2023 +0100

    Update for Hunspell 1.7.2 and LibreOffice 7.5

...
--- a/szotar/ifjusagi/ragozatlan.2
+++ b/szotar/ifjusagi/ragozatlan.2
+random [adj]

Köszönöm a hibajelzést!
